# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

services:
  mongo:
    image: mongo-amd:latest
    pull_policy: never
    container_name: mongo-access
    restart: always
    environment:
      MONGO_INITDB_DATABASE: access
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_NON_ROOT_USERNAME: ianode-access
      MONGO_NON_ROOT_PASSWORD: password
    networks:
      - auth
    volumes:
      - ../init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'echo ''db.runCommand("ping").ok'' | mongosh localhost:27017/test --quiet',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  access-api:
    image: 127214183387.dkr.ecr.eu-west-2.amazonaws.com/ianode-access:latest
    container_name: access-api-ianode
    pull_policy: always
    restart: always
    networks:
      - auth
    ports:
      - 8091:8091
    environment:
      - OPENID_PROVIDER_URL=https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_oGJ7rFJsw
      - DEPLOYED_DOMAIN =http://localhost:3000
      - MONGO_RETRY_REWRITES=false
      - MONGO_URL=ndtp-testing-cluster.cluster-cba842oso29b.eu-west-2.docdb.amazonaws.com:27017
      - MONGO_PROTOCOL=mongodb
      - MONGO_PWD=${MONGO_PWD}
      - MONGO_COLLECTION=access
      - MONGO_USER=${MONGO_USER}
      - MONGO_SSL_CERT=../ianodeconfig/mongocert.pem
      - SCIM_ENABLED=true
      - GROUPS_KEY=cognito:groups
      - DEBUG="true"
      - PORT=8091
    volumes:
      - type: bind
        source: ../ianodeconfig
        target: /ianodeconfig
    command: ["node", "dist/index.js"]

  secure-agent-graph-container:
    image: 127214183387.dkr.ecr.eu-west-2.amazonaws.com/secure-agent-graph:latest
    container_name: secure-agent-graph-container
    networks:
      - auth
    ports:
      - "3030:3030"
    environment:
      - JAVA_OPTIONS=-Xmx2048m -Xms2048m
      - JWKS_URL=https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_oGJ7rFJsw/.well-known/jwks.json
      - USER_ATTRIBUTES_URL=http://access-api:8091
    volumes:
      - type: bind
        source: ../sag-docker/mnt/logs
        target: /fuseki/logs
      - type: bind
        source: ../sag-docker/mnt/databases
        target: /fuseki/databases
      - type: bind
        source: ../sag-docker/mnt/config
        target: /fuseki/config
    command: "--config config/config-abac-local.ttl"
networks:
  auth:
    name: auth
volumes:
  mongo-data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
